name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20, 22]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
    
    - name: Run configuration tests
      run: node test-config.js
    
    - name: Run catalog tests
      run: node test-catalog-simple.js
    
    - name: Run runtime tests
      run: node test-runtime.js
    
    - name: Run all tests
      run: node run-all-tests.js
    
    - name: Check for native dependencies
      run: |
        if npm list isolated-vm better-sqlite3; then
          echo "Native dependencies found - attempting rebuild"
          npm rebuild isolated-vm better-sqlite3 || echo "Native rebuild failed - may need different Node.js version"
        fi
    
    - name: Lint check
      run: |
        if [ -f "yarn.lock" ]; then
          yarn lint:all
        fi
      continue-on-error: true

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4